[package]
name = "beyond_squared_hid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hidapi = "2.6.0"
egui = "0.26.2"
eframe = "0.26.2"
